bi_encoder:
  batch_size: 64
  model_name: all-MiniLM-L6-v2
  top_k: 100
bm25:
  top_k: 500
cross_encoder:
  batch_size: 32
  model_name: cross-encoder/ms-marco-MiniLM-L-6-v2
  top_k: 50
faiss:
  M: 32
  efConstruction: 200
  efSearch: 64
  index_type: HNSW
